version: '3.5'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
  
  api:
    build:
      context: .
    restart: always
    depends_on:
      - db
    tty: true
    env_file:
      - .env
    ports:
      - 6789:6789

